### ISSUE TITLE
Añadir columna con precio en tabla de depas y estudios

### ISSUE THREAD

**Issue by TuOdoo** [MerxBusinessPerformance/barriotec1#15]
Añadir una columna con titulo "precio" y poner la cantidad del precio del producto "list.price" ubicado en Booking / Productos / Product template / General information / Sales price. La columna debe ser agregada entre Balcón y Estado

**Comment by RafaelAngelRamirez** [comment]
Resultado aplicado a testweb...
![image](https://user-images.githubusercontent.com/27775245/144105325-27a06b62-61f7-4404-b6bc-d13155ab48da.png)
